### ISSUE TITLE
What is the original source of the lists?

### ISSUE THREAD

**Issue by cybermonkee** [Enkidu-6/tor-relay-lists#1]
Hi, I am just wondering what the original source of the list is and how you parse it?

**Comment by Enkidu-6** [comment]
The lists are pulled directly from onionoo and filtered based on the kind of list needed.

https://onionoo.torproject.org/details?type=relay&running=true

**Comment by cybermonkee** [comment]
I did it like this: 

curl -s 'https://onionoo.torproject.org/details?search=running:true' -o - | jq -cr '.relays[].or_addresses[0]' | sort -u | awk 'BEGIN {FS =":"}; {print $1}' | uniq -d

**Comment by Enkidu-6** [comment]
Sounds good. There are plenty of ways to filter the list and yours is as good as any. You can also try to pull a cleaner and leaner list to make the filtering easier like this list:

https://onionoo.torproject.org/details?type=relay&running=true&fields=or_addresses

There are two reasons I didn't include the original filtering in tor-ddos scripts. One, because it could make the scripts longer and more complicated for the average Joe to figure out and modify and the other is because I promised to make scripts that anyone with any basic popular linux distro can run without having to deal with dependencies to download. "jq" is something that doesn't come out of the box with a lot of distros and has to be separately downloaded.
