### ISSUE TITLE
The day is written on the last line on some files

### ISSUE THREAD

**Issue by maherbo** [Enkidu-6/tor-relay-lists#4]
On these files:

- 2-or.txt
- 2-or-v6.txt

The day is written on the last line causing the following error when executed (on a Tuesday in this case):

```
ipset v7.15: Syntax error: cannot parse Tue: resolving to IPv6 address failed
```

It never happened before.

**Comment by Enkidu-6** [comment]
Hi, Thank you for bringing it to my attention. I haven't made any changes to the filters, Something in the format of the response from onionoo must have changed. I'll look into it.

In the meanwhile, the rule for adding them to the ipset is processed line by line. Any error you're getting is for that line alone and it shouldn't affect the rest of them. Your ipset is still populated with the rest.

**Comment by Enkidu-6** [comment]
The problem is fixed. Somewhere in the script for sorting the list, I have ``` | grep ' 2 ' ``` to pick up the IP addresses with 2 ORPorts. That directive was also picking up the line with the date because it's ``` Tue May 2 ```. I'm assuming this problem was occurring every second day of each month and we never noticed it.

I fixed the script to make sure it won't happen again on June the second. 

Thanks for noticing.
